lint-passengers:
  only:
    - merge_requests
  tags:
    - twl-monorepo-shell
  stage: lint
  before_script:
    - echo $PATH
    - source ~/.bashrc
    - echo $PATH
    - npm -v
    - yarn -v
    - node -v
    - aws --version
    - find ./apps -mindepth 1 -not -path "./apps/walts-vault-mystery-frontend*" -delete
    - yarn install --pure-lockfile
  script:
    - echo "LINT"
    - yarn workspace walts-vault-mystery-frontend lint

deploy-walts-vault-mystery-frontend-production:
  only:
    - walts-vault-mystery-frontend-production
  tags:
    - twl-monorepo-shell
  stage: deploy
  before_script:
    - echo $PATH
    - source ~/.bashrc
    - echo $PATH
    - npm -v
    - yarn -v
    - node -v
    - aws --version
    - find ./apps -mindepth 1 -not -path "./apps/walts-vault-mystery-frontend*" -delete
    - yarn install --pure-lockfile
  script:
    - echo "DEPLOY"
    - yarn workspace walts-vault-mystery-frontend deploy
  environment:
    name: production
    url: https://mclxxmii.xyz
